name: Publish Github Pages Sphinx

on:
  push:
    branches:
      - translate
  pull_request:
    branches:
      - translate

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout your repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt

    # 4. Run sphinx-apidoc
    - name: Generate API documentation
      run: |
        sphinx-apidoc -o docs kobo_provider

    # 5. Build the HTML docs (opcional)
    - name: Build HTML documentation
      run: |
        sphinx-build -b html docs docs/_build/html

     # 6. Generate .pot files for i18n
    - name: Generate .pot files
      run: |
        sphinx-build -b gettext docs i18n/pot

    # 7. Update .po files for translation
    - name: Update .po files
      run: |
        sphinx-intl update -p i18n/pot -l en
        sphinx-intl update -p i18n/pot -l es

    # 8. Build .mo files
    - name: Build .mo files
      run: |
        sphinx-intl build

    # 9. Commit and push the generated documentation and translation files
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/_build/html docs/*.rst i18n locale/en/LC_MESSAGES locale/es/LC_MESSAGES
        git commit -m "Auto-update documentation and translation files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
